from setuptools import setup, find_packages
import subprocess

setup(
    name="yeager_utils",
    version="1.0",
    description='Helpful utilities',
    author='Travis R. Yeager',
    author_email='yeager7@llnl.gov',
    packages=find_packages(),
    install_requires=[
        'astropy',
        'astroquery',
        'cmake',
        'corner',
        'emcee',
        'gitpython',
        'h5py',
        'imageio',
        'ipykernel',
        'ipython',
        'ipytree',
        'ipyvolume',
        'ipympl',
        'jplephem',
        'lmfit',
        'matplotlib',
        'mpmath',
        'numpy',
        'nexusformat',
        'npy-append-array',
        'opencv-python',
        'pandas',
        'pickle4',
        'pillow',
        'psutil',
        'pybind11',
        'pyerfa',
        'PyPDF2',
        'pytest',
        'pytest-mpi',
        'python-xlib',
        'rebound',
        'requests',
        'regex',
        'scikit-learn',
        'seaborn',
        'sympy',
        'tqdm',
        'vg',
        'yapf',
    ],
    zip_safe=False,
    include_package_data=True,
)
