import json
from io import StringIO
from types import SimpleNamespace

import numpy as np
import pytest

from ssapy_toolkit.io import (
    ReferenceCaseSegment,
    compare_reference_case,
    read_oem,
    read_reference_case,
    write_reference_case,
)


def test_reference_case_oem_round_trip_reads_si_states(tmp_path):
    trajectory = SimpleNamespace(
        t=np.array([10.0, 12.5]),
        r=np.array([[7_000_000.0, 0.0, 0.0], [7_000_001.0, 10.0, 20.0]]),
        v=np.array([[0.0, 7_500.0, 0.0], [-1.0, 7_500.5, 2.0]]),
    )
    files = write_reference_case(trajectory, tmp_path, epoch="2025-01-01T00:00:00Z", case_name="round_trip")

    loaded = read_reference_case(files.metadata_path)
    assert loaded.metadata["case_name"] == "round_trip"
    np.testing.assert_allclose(loaded.t, trajectory.t, atol=1e-12)
    np.testing.assert_allclose(loaded.r, trajectory.r, atol=1e-9)
    np.testing.assert_allclose(loaded.v, trajectory.v, atol=1e-9)
    residuals = compare_reference_case(trajectory, files.ephemeris_path)
    assert residuals["max_position_m"] < 1e-8
    assert residuals["max_velocity_m_s"] < 1e-8
    np.testing.assert_allclose(read_reference_case(files.ephemeris_path).r, trajectory.r, atol=1e-9)


def _multi_segment_oem():
    return """CCSDS_OEM_VERS = 2.0
CREATION_DATE = 2025-001T00:00:00.000000
ORIGINATOR = OREKIT
COMMENT generated by an inline fixture
META_START
COMMENT first segment
OBJECT_NAME = TEST-SAT
OBJECT_ID = 1998-067A
CENTER_NAME = Earth
REF_FRAME = GCRF
TIME_SYSTEM = UTC
START_TIME = 2025-001T00:00:00.000000
STOP_TIME = 2025-001T00:00:01.000000
META_STOP
2025-001T00:00:00.000000 1.0D+03 2 3 4 5 6
2025-001T00:00:01.000000 1.001D+03 2 3 4 5 6
META_START
COMMENT second segment
OBJECT_NAME = TEST-SAT
OBJECT_ID = 1998-067A
CENTER_NAME = Earth
REF_FRAME = GCRF
TIME_SYSTEM = UTC
START_TIME = 2025-001T00:00:02.000000
STOP_TIME = 2025-001T00:00:03.000000
META_STOP
2025-001T00:00:02.000000 1.002D+03 2 3 4 5 6
2025-001T00:00:03.000000 1.003D+03 2 3 4 5 6
"""


def test_read_oem_supports_inline_orekit_style_multi_segment_and_si_conversion():
    loaded = read_oem(StringIO(_multi_segment_oem()))

    assert isinstance(loaded.segments[0], ReferenceCaseSegment)
    assert loaded.metadata["segment_count"] == 2
    assert loaded.metadata["ORIGINATOR"] == "OREKIT"
    assert loaded.segments[0].comments == ("first segment",)
    assert loaded.segments[1].comments == ("second segment",)
    np.testing.assert_allclose(loaded.t, [0.0, 1.0, 2.0, 3.0])
    np.testing.assert_allclose(loaded.r[:, 0], [1.0e6, 1.001e6, 1.002e6, 1.003e6])
    np.testing.assert_allclose(loaded.v[0], [4.0e3, 5.0e3, 6.0e3])
    assert loaded.acceleration is None


@pytest.mark.parametrize("time_system", ["UTC", "TAI", "TT", "TDB", "TCB", "TCG", "UT1", "GPS"])
@pytest.mark.parametrize("date", ["2025-001", "2025-01-01"])
def test_read_oem_supports_absolute_time_systems_and_epoch_formats(time_system, date):
    source = _multi_segment_oem().replace("TIME_SYSTEM = UTC", f"TIME_SYSTEM = {time_system}")
    loaded = read_oem(source.replace("2025-001", date))
    np.testing.assert_allclose(loaded.t, [0.0, 1.0, 2.0, 3.0], atol=1e-9)


def test_read_reference_case_applies_absolute_gps_epoch_and_segment_offsets(tmp_path):
    oem_path = tmp_path / "gps.oem"
    oem_path.write_text(_multi_segment_oem().replace("TIME_SYSTEM = UTC", "TIME_SYSTEM = GPS"))
    metadata_path = tmp_path / "gps.json"
    metadata_path.write_text(json.dumps({
        "epoch": "2024-12-31T23:59:42Z",
        "time_origin_s": 10.0,
        "sample_count": 4,
        "files": {"ephemeris": oem_path.name},
    }))

    loaded = read_reference_case(metadata_path)
    np.testing.assert_allclose(loaded.t, [10.0, 11.0, 12.0, 13.0], atol=1e-9)
    np.testing.assert_allclose(loaded.segments[0].t, [10.0, 11.0], atol=1e-9)
    np.testing.assert_allclose(loaded.segments[1].t, [12.0, 13.0], atol=1e-9)


def test_read_oem_handles_valid_utc_leap_second():
    source = _multi_segment_oem().split("META_START\nCOMMENT second", 1)[0]
    source = source.replace("START_TIME = 2025-001T00:00:00.000000", "START_TIME = 2016-12-31T23:59:59")
    source = source.replace("STOP_TIME = 2025-001T00:00:01.000000", "STOP_TIME = 2017-01-01T00:00:00")
    source = source.replace(
        "2025-001T00:00:00.000000 1.0D+03 2 3 4 5 6\n"
        "2025-001T00:00:01.000000 1.001D+03 2 3 4 5 6\n",
        "2016-12-31T23:59:59 1.0D+03 2 3 4 5 6\n"
        "2016-12-31T23:59:60 1.001D+03 2 3 4 5 6\n"
        "2017-01-01T00:00:00 1.002D+03 2 3 4 5 6\n",
    )
    np.testing.assert_allclose(read_oem(source).t, [0.0, 1.0, 2.0], atol=1e-9)


def _covariance_block(epoch, frame="RTN", diagonal=1.0):
    return f"""COVARIANCE_START
EPOCH = {epoch}
COV_REF_FRAME = {frame}
{diagonal}
0 {diagonal}
0 0 {diagonal}
0 0 0 {diagonal}
0 0 0 0 {diagonal}
0 0 0 0 0 {diagonal}
COVARIANCE_STOP
"""


def test_read_oem_preserves_covariance_epochs_frames_and_si_units():
    source = _multi_segment_oem()
    source = source.replace(
        "2025-001T00:00:01.000000 1.001D+03 2 3 4 5 6\nMETA_START",
        "2025-001T00:00:01.000000 1.001D+03 2 3 4 5 6\n"
        + _covariance_block("2025-001T00:00:00.500000", diagonal=2.0)
        + "META_START",
    )
    source += _covariance_block("2025-001T00:00:03.000000", diagonal=3.0)
    loaded = read_oem(source)

    np.testing.assert_allclose(loaded.covariance_t, [0.5, 3.0])
    np.testing.assert_allclose(np.diag(loaded.covariance[0]), np.full(6, 2.0e6))
    np.testing.assert_allclose(np.diag(loaded.covariance[1]), np.full(6, 3.0e6))
    assert loaded.covariance_reference_frame == "RTN"
    assert loaded.segments[0].covariance_reference_frame == "RTN"
    assert loaded.segments[1].covariance_reference_frame == "RTN"


def test_write_reference_case_round_trips_covariance_and_sidecar_offsets(tmp_path):
    trajectory = SimpleNamespace(
        t=np.array([10.0, 12.5]),
        r=np.array([[7_000_000.0, 0.0, 0.0], [7_000_001.0, 10.0, 20.0]]),
        v=np.array([[0.0, 7_500.0, 0.0], [-1.0, 7_500.5, 2.0]]),
    )
    covariance = np.stack((np.eye(6) * 4.0, np.eye(6) * 9.0))
    files = write_reference_case(
        trajectory,
        tmp_path,
        epoch="2025-01-01T00:00:00Z",
        covariance=covariance,
        covariance_t=[0.0, 2.5],
        covariance_reference_frame="RIC",
    )

    loaded = read_reference_case(files.metadata_path)
    np.testing.assert_allclose(loaded.covariance_t, [10.0, 12.5])
    np.testing.assert_allclose(loaded.covariance, covariance)
    assert loaded.covariance_reference_frame == "RIC"
    metadata = json.loads(files.metadata_path.read_text())
    assert metadata["covariance_count"] == 2
    assert metadata["covariance_reference_frame"] == "RIC"


def _acceleration_multi_segment_oem():
    return _multi_segment_oem().replace(" 4 5 6", " 4 5 6 1e-3 2e-3 3e-3")


def test_read_oem_preserves_acceleration_across_segments_in_si_units():
    loaded = read_oem(_acceleration_multi_segment_oem())

    np.testing.assert_allclose(loaded.acceleration_t, [0.0, 1.0, 2.0, 3.0])
    np.testing.assert_allclose(loaded.acceleration, np.tile([1.0, 2.0, 3.0], (4, 1)))
    np.testing.assert_allclose(loaded.segments[0].acceleration_t, [0.0, 1.0])
    np.testing.assert_allclose(loaded.segments[1].acceleration, [[1.0, 2.0, 3.0]] * 2)
    assert loaded.metadata["acceleration_count"] == 4
