#!/usr/bin/env python3
"""
demo_orbit_plot.py
------------------
Visualises the Keplerian conic generated from a single state vector
using ellipse_from_rv(), and plots the corresponding velocity history.

All units are SI.
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 – registers 3‑D projection

# --- local imports -----------------------------------------------------------
from yeager_utils import ellipse_from_rv, RGEO, VGEO, pprint
# -----------------------------------------------------------------------------


def main():
    # Example inertial state vector (LEO‑like)
    r0 = np.array([RGEO, 0.0, 0.0])              # position [m]
    v0 = np.array([0.0, 0.9 * VGEO, VGEO])      # velocity [m s⁻¹]

    # Generate samples (positions r and velocities v)
    info = ellipse_from_rv(r0, v0, num=720)        # 720 points → 0.5° steps
    pprint(info)
    r = info['r']
    v = info['v']
    # ── Plot 1: 3‑D trajectory ──────────────────────────────────────────────
    fig1 = plt.figure(figsize=(7, 7))
    ax1 = fig1.add_subplot(111, projection='3d')
    ax1.plot(r[:, 0], r[:, 1], r[:, 2], lw=1.2, label='Orbit path')
    ax1.scatter(*r0, c='crimson', s=40, marker='o', label='Initial position')

    ax1.set_xlabel('x [m]')
    ax1.set_ylabel('y [m]')
    ax1.set_zlabel('z [m]')
    ax1.set_title('Orbit generated by ellipse_from_rv()', pad=12)
    ax1.legend()
    ax1.set_box_aspect([1, 1, 1])     # equal aspect
    plt.tight_layout()

    # ── Plot 2: velocity components over sample index (time proxy) ──────────
    fig2, ax2 = plt.subplots(figsize=(8, 4))
    idx = np.arange(len(v))
    ax2.plot(idx, np.linalg.norm(v, axis=-1), label='total')
    ax2.plot(idx, v[:, 0], label='vx', linestyle='--')
    ax2.plot(idx, v[:, 1], label='vy', linestyle='--')
    ax2.plot(idx, v[:, 2], label='vz', linestyle='--')
    ax2.set_xlabel('Sample index (uniform Δtrue‑anomaly)')
    ax2.set_ylabel('Velocity [m/s]')
    ax2.set_title('Velocity along orbit')
    ax2.grid(True, linestyle='--', alpha=0.6)
    ax2.legend()

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
